services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: bca_backend
    ports:
      - "8080:8080"
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bca_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
